### PR TITLE
Broken sorting in SQLConsole

### LINKED ISSUE #55: SQL Console - Query results - Sorting not working as expected
## Description

Sorting does apply correct order to SQL console results.

## Steps to reproduce

* Execute a select query to get results in the results section.
* In the Results Section, click on any column name to sort in ascending order.
* In the Results Section, click on same column name to sort in descending order.
* Click on any other column to sort as per ascending order of that column

## Current behavior

Sorting is not working as expected.

image-2018-08-21-13-06-38-625

## Expected behavior

Sorting should be working as expected.

### PR DESCRIPTION
**Pull request by mean2me**
Fixed broken javascript for table sorting in PB -> Settings -> SQLConsole

fixes #55

### CODE REVIEW

File: Extensions/Settings/Dnn.PersonaBar.SqlConsole/admin/personaBar/scripts/sort.js [hunk 1]
```diff
@@ -24,7 +24,7 @@ define(['jquery', 'knockout'], function ($, ko) {
 
     var changeSort = function (e) {
         var $element = $(e.target);
-        var viewModel = ko.dataFor($element.parent()[0]);
+        var viewModel = ko.dataFor($element.parent().parent().parent()[0]);
```
Comment (tpluscode) [inline Extensions/Settings/Dnn.PersonaBar.SqlConsole/admin/personaBar/scripts/sort.js:27]: This is an awkward construct and potentially brittle in case of changes to element hierarchy. Is there no other way to get that view model?

Comment (mean2me) [reply Extensions/Settings/Dnn.PersonaBar.SqlConsole/admin/personaBar/scripts/sort.js:27]: If we plan to redesign this module and migrate to a modern framework, I would totally agree and we can of course make it better. I just fixed a bug avoiding any kind of breaking change. I don't think it's worth to refactor a Knockout based module since it won't be anything much better than now. If you don't like the .parent() approach, we can use DOM ids or class names, but it would be an enhancement, not a fix and it would require changes in current DOM structure.

Comment (tpluscode) [reply Extensions/Settings/Dnn.PersonaBar.SqlConsole/admin/personaBar/scripts/sort.js:27]: Sure, that's why I marked this as comment and not "changes requested". 

Yes, changes to existing DOM structured won't do much good. I'm more asking if this is the best approach for current codebase.

**Review by tpluscode — APPROVED** [review]
Guess we should let it go for legacy jQuery/knockout components. Agreed @dnnsoftware/tag

**Review by mitchelsellers — APPROVED** [review]
The TAG group has discussed this and approving as-is.
